default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: welcometotrika
  port: 5432
  database: DevcampPortfolio_development

test:
  <<: *default
  database: DevcampPortfolio_test
  username: postgres
  password: welcometotrika

production:
  <<: *default
  database: DevcampPortfolio_production
  username: DevcampPortfolio
  password: <%= ENV['DEVCAMPPORTFOLIO_DATABASE_PASSWORD'] %>
